name: Build Docker Image
on:
  push:
    branches:
      - master
jobs:

  generatetag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
  
  build:
    needs: [generatetag]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Build the image
      run: docker build -t rati-bot:${{ steps.previoustag.outputs.tag }} .
    - name: Docker login
      run: docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}
    - name: Docker image tag
      run: docker tag rati-bot:v$GITHUB_TAG_NAME restfulleo/rati-bot:${{ steps.previoustag.outputs.tag }}
    - name: Push image
      run: docker push restfulleo/rati-bot:${{ steps.previoustag.outputs.tag }}
