name: Bump version
on:
  push:
    branches:
      - master
jobs:

  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
  
  build:
    needs: [tag]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Get tag name
      uses: olegtarasov/get-tag@v1
    - name: Build the image
      run: docker build -t rati-bot:v$GITHUB_TAG_NAME .
    - name: Docker login
      run: docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}
    - name: Docker image tag
      run: docker tag rati-bot:v$GITHUB_TAG_NAME restfulleo/rati-bot:v$GITHUB_TAG_NAME
    - name: Push image
      run: docker push restfulleo/rati-bot:v$GITHUB_TAG_NAME
