name: Docker Image CI

on: 
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Move to Rati-bot source directory
      run: ls
    - name: Build the image
      run: docker build -t rati-bot:v11 .
    - name: Docker login
      run: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
    - name: Docker image tag
      run: docker tag rati-bot:v11 restfulleo/rati-bot:v11
    - name: Push image
      run: docker push restfulleo/rati-bot:v11
