name: Docker Image CI

on: 
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: DockerFile
