name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build the image
      run: docker build -t rati-bot:v${{ steps.get_version.outputs.VERSION }} .
    - name: Docker login
      run: docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}
    - name: Docker image tag
      run: docker tag rati-bot:v${{ steps.get_version.outputs.VERSION }} restfulleo/rati-bot:v${{ steps.get_version.outputs.VERSION }}
    - name: Push image
      run: docker push restfulleo/rati-bot:v${{ steps.get_version.outputs.VERSION }}
